### ISSUE TITLE
Java exception on run

### ISSUE THREAD

**Issue by andrevdm** [bbinet/docker-mplabx#1]
I'm getting an exception on startup
   opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/nbexec: line 474:   141 Aborted

Have you seen this before? 

I forked and will push a change to add the xc8 compiler as well once this is fixed.

Thanks

**Comment by bbinet** [comment]
No, I've never seen this exception on startup. Does it prevent mplabx ide to start?

**Comment by andrevdm** [comment]
Yeah, it wont start at all. I've pulled & rebuild from the docker file, both break with the same issue. I can use lmartorell/mplabxide and that works. So it must be something environmental. 

The core dump message is

```
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x8d28]
```

**Comment by bbinet** [comment]
Actually, I was able to reproduce the issue with the latest docker image:

```
$ docker run -it --name mplabx_test --privileged -v /dev/bus/usb:/dev/bus/usb -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/bruno/dev/TR:/home/bruno/dev/TR -e DISPLAY=unix$DISPLAY bbinet/mplabx
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffa3853bd28, pid=141, tid=140710000252672
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [ld-linux-x86-64.so.2+0x8d28]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# //hs_err_pid141.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/nbexec: line 474:   141 Aborted                 "/opt/microchip/mplabx/v3.15/sys/java/jre1.8.0_60/bin/java" -Djdk.home="/opt/microchip/mplabx/v3.15/sys/java/jre1.8.0_60" -classpath "/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/boot.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/org-openide-modules.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/org-openide-util-lookup.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/org-openide-util.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/locale/boot_zh_CN.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/locale/org-openide-modules_zh_CN.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/opt/microchip/mplabx/v3.15/mplab_ide/platform/lib/locale/org-openide-util_zh_CN.jar" -Dnetbeans.default_userdir_root="/root/.mplab_ide" -Dnetbeans.dirs="/opt/microchip/mplabx/v3.15/mplab_ide/mplab_ide:/opt/microchip/mplabx/v3.15/mplab_ide/cnd:/opt/microchip/mplabx/v3.15/mplab_ide/dlight:/opt/microchip/mplabx/v3.15/mplab_ide/harness:/opt/microchip/mplabx/v3.15/mplab_ide/ide:/opt/microchip/mplabx/v3.15/mplab_ide/mdbcore:/opt/microchip/mplabx/v3.15/mplab_ide/mplablibs:/opt/microchip/mplabx/v3.15/mplab_ide/nb:" -Dnetbeans.home="/opt/microchip/mplabx/v3.15/mplab_ide/platform" '-Dnetbeans.importclass=org.netbeans.upgrade.AutoUpgrade' '-Djava.io.tmpdir=/tmp/mplab_ide' '-Dcrownking.stream.verbosity=very-quiet' '-Xss2m' '-Xms256m' '-XX:PermSize=128m' '-XX:MaxPermSize=384m' '-Xmx512m' '-Dapple.awt.graphics.UseQuartz=true' '-XX:+UseConcMarkSweepGC' '-XX:+CMSClassUnloadingEnabled' '-Dapt.limit.expanded.params=1000' '-Dplugin.manager.check.interval=EVERY_DAY' -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/root/.mplab_ide/dev/v3.15/var/log/heapdump.hprof" org.netbeans.Main --cachedir "/root/.cache/mplab_ide/dev/v3.15/var" --userdir "/root/.mplab_ide/dev/v3.15" "--branding" "mplab" 0<&0
```

I need to take time to investigate on this: maybe early next year ;)

**Comment by andrevdm** [comment]
At least it is consistent then. I'll see if I can find some time to investigate as well.

Thanks again

**Comment by bbinet** [comment]
Here is the full error log:
[hs_err_pid142.txt](https://github.com/bbinet/docker-mplabx/files/126708/hs_err_pid142.txt)

But I don't have any idea of why it crashes...

**Comment by bbinet** [comment]
It seems this issue is fixed with the latest v3.20 mplabx release unless you click on the "mplabx store" tab.
So I'm closing this tab, and it now works for me again.

**Comment by andrevdm** [comment]
Great news. Thanks for the update!

**Comment by anderwm** [comment]
Three years later and MPLABX 5.15 still crashes if you click on the store tab. Classic Microchip
